### PR TITLE
Resolve Various Issues in Azure Transport

### PR DESCRIPTION
**Pull request by petedavis**
Fixes:
 - Azure 50 character limit on topic subscription names
 - Topics not created for derived types of published messages
 - Check to see if topics and queues exist before creating.
 - Update nuget packages inline with masstransit 2.9.9
 - Update rakefile to support albacore v 1.0.0
 - Update nuget package restore to use nuget.exe restore command to restore the solution file packages to be more consistent with building in visual studio.

### CODE REVIEW

**Comment by petedavis** [comment]
@phatboyg would it be possible to get this reviewed and a new nuget version released? I have updated the .semver file to 0.3. The version that is on nuget.org is not really usable in its current state.

**Comment by phatboyg** [comment]
I'm fine pulling this in, but the rakefile bombs on me for some reason.

**Comment by petedavis** [comment]
The versions of albacore that I have installed are:
albacore (1.0.0, 0.3.6)

Which version are you using across the MT projects?

**Comment by petedavis** [comment]
I think I have found the error:
NoMethodError: undefined method `options' for #<NUnit:0x0000000342f2b8>
I haven't been running the tests rake. Ill have a look at that.

**Comment by phatboyg** [comment]
Yep that's the one. 

____
Chris Patterson

**Comment by petedavis** [comment]
The rake nunit task runner is fixed. The nunit task had changed. Still a few test failures to look at.

**Comment by petedavis** [comment]
All the tests are now working for me in visual studio, but not when running rake. Might have to look at my environment. Im getting a 401 unauthorized in the console.

**Pull request closed without merging**
